# Generated by Django 5.1.6 on 2025-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_rename_date_enrolled_enrollment_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerregistration',
            name='role',
            field=models.CharField(default='trainer', max_length=20),
        ),
    ]
