# Generated by Django 5.1.6 on 2025-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_trainerregistration_user_learnerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerregistration',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
